sudo: false
language: go
addons:
  apt:
    sources:
    - sourceline: 'ppa:duggan/bats'
    packages:
    - bats
    - bc
script:
  - go get -u github.com/golang/dep/cmd/dep
  - make clean vendor all install
  - make test
  - make test-unit
